name: Testing workflow
run-name: Testing workflow
on:
  push:
    branches: [ test ]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.301'

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Restore dependencies
        working-directory: ./src
        run: dotnet restore

      - name: Run unit tests via Makefile
        run: make unit_tests
        
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.301'

      - name: Restore and Build
        run: |
          dotnet restore ./src/currency-converter.sln
          dotnet build ./src/currency-converter.sln --configuration Release --no-restore

      - name: Start WireMock and Wait
        run: make wiremock_up

      - name: Run Integration Tests
        run: make integration_tests

      - name: Stop WireMock
        if: always()
        run: make wiremock_down