name: Testing workflow
run-name: Testing workflow
on:
  push:
    branches: [ test ]
  workflow_dispatch:

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run k6 in Docker Compose
        run: make load_tests_in_compose

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK Preview
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.0-preview.7.23321.9'

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Restore dependencies
        working-directory: ./src
        run: dotnet restore

      - name: Run unit tests via Makefile
        run: make unit_tests
